// questions.js
// 2025/2026 Civics Test — 128 Questions (MCQ version for your quiz UI)

export const questions = [
  {
    id: 1,
    question: "What is the form of government of the United States?",
    options: ["Republic", "Monarchy", "Dictatorship", "Theocracy"],
    choices: ["Republic", "Monarchy", "Dictatorship", "Theocracy"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 2,
    question: "What is the supreme law of the land?",
    options: ["The Constitution", "The Declaration of Independence", "The Bill of Rights", "The Articles of Confederation"],
    choices: ["The Constitution", "The Declaration of Independence", "The Bill of Rights", "The Articles of Confederation"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 3,
    question: "Which is one thing the U.S. Constitution does?",
    options: ["Defines the powers of government", "Elects the President", "Declares independence from France", "Creates the Supreme Court building"],
    choices: ["Defines the powers of government", "Elects the President", "Declares independence from France", "Creates the Supreme Court building"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 4,
    question: 'The U.S. Constitution starts with "We the People." What does this mean?',
    options: ["Self-government", "Rule by a king", "Government by the military", "Government by corporations"],
    choices: ["Self-government", "Rule by a king", "Government by the military", "Government by corporations"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 5,
    question: "How are changes made to the U.S. Constitution?",
    options: ["Amendments", "Executive orders", "Court opinions", "State laws"],
    choices: ["Amendments", "Executive orders", "Court opinions", "State laws"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 6,
    question: "What does the Bill of Rights protect?",
    options: ["(The basic) rights of people living in the United States", "Only the rights of the President", "Only state government powers", "Only military rules"],
    choices: ["(The basic) rights of people living in the United States", "Only the rights of the President", "Only state government powers", "Only military rules"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 7,
    question: "How many amendments does the U.S. Constitution have?",
    options: ["Twenty-seven (27)", "Ten (10)", "Fifty (50)", "One hundred (100)"],
    choices: ["Twenty-seven (27)", "Ten (10)", "Fifty (50)", "One hundred (100)"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 8,
    question: "Why is the Declaration of Independence important?",
    options: ["It says all people are created equal", "It created the U.S. Senate", "It ended World War II", "It established the Federal Reserve"],
    choices: ["It says all people are created equal", "It created the U.S. Senate", "It ended World War II", "It established the Federal Reserve"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 9,
    question: "What founding document said the American colonies were free from Britain?",
    options: ["Declaration of Independence", "U.S. Constitution", "Bill of Rights", "Mayflower Compact"],
    choices: ["Declaration of Independence", "U.S. Constitution", "Bill of Rights", "Mayflower Compact"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 10,
    question: "Which is an important idea from the Declaration of Independence and the U.S. Constitution?",
    options: ["Liberty", "Absolute monarchy", "One-party rule", "Military dictatorship"],
    choices: ["Liberty", "Absolute monarchy", "One-party rule", "Military dictatorship"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 11,
    question: 'The words "Life, Liberty, and the pursuit of Happiness" are in what document?',
    options: ["Declaration of Independence", "U.S. Constitution", "Federalist Papers", "Emancipation Proclamation"],
    choices: ["Declaration of Independence", "U.S. Constitution", "Federalist Papers", "Emancipation Proclamation"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 12,
    question: "What is the economic system of the United States?",
    options: ["Capitalism", "Feudalism", "Communism", "Mercantilism"],
    choices: ["Capitalism", "Feudalism", "Communism", "Mercantilism"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 13,
    question: 'What is the "rule of law"?',
    options: ["No one is above the law", "Only leaders must follow the law", "Only citizens must follow the law", "The President can ignore laws"],
    choices: ["No one is above the law", "Only leaders must follow the law", "Only citizens must follow the law", "The President can ignore laws"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 14,
    question: "Many documents influenced the U.S. Constitution. Name one.",
    options: ["Mayflower Compact", "Monroe Doctrine", "Marshall Plan", "Louisiana Purchase"],
    choices: ["Mayflower Compact", "Monroe Doctrine", "Marshall Plan", "Louisiana Purchase"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 15,
    question: "There are three branches of government. Why?",
    options: ["Checks and balances", "To make laws faster", "To elect governors", "To replace state governments"],
    choices: ["Checks and balances", "To make laws faster", "To elect governors", "To replace state governments"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 16,
    question: "Name the three branches of government.",
    options: ["Legislative, Executive, Judicial", "President, Congress, Cabinet", "States, Cities, Courts", "Army, Navy, Air Force"],
    choices: ["Legislative, Executive, Judicial", "President, Congress, Cabinet", "States, Cities, Courts", "Army, Navy, Air Force"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 17,
    question: "The President of the United States is in charge of which branch?",
    options: ["Executive branch", "Legislative branch", "Judicial branch", "State government"],
    choices: ["Executive branch", "Legislative branch", "Judicial branch", "State government"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 18,
    question: "What part of the federal government writes laws?",
    options: ["U.S. Congress", "The Supreme Court", "The President", "The Cabinet"],
    choices: ["U.S. Congress", "The Supreme Court", "The President", "The Cabinet"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 19,
    question: "What are the two parts of the U.S. Congress?",
    options: ["Senate and House of Representatives", "President and Vice President", "Supreme Court and Federal Courts", "Governors and Mayors"],
    choices: ["Senate and House of Representatives", "President and Vice President", "Supreme Court and Federal Courts", "Governors and Mayors"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 20,
    question: "Name one power of the U.S. Congress.",
    options: ["Declares war", "Appoints federal judges", "Writes the Constitution", "Runs elections in every state"],
    choices: ["Declares war", "Appoints federal judges", "Writes the Constitution", "Runs elections in every state"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 21,
    question: "How many U.S. Senators are there?",
    options: ["One hundred (100)", "Fifty (50)", "Four hundred thirty-five (435)", "Twenty-seven (27)"],
    choices: ["One hundred (100)", "Fifty (50)", "Four hundred thirty-five (435)", "Twenty-seven (27)"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 22,
    question: "How long is a term for a U.S. Senator?",
    options: ["Six (6) years", "Two (2) years", "Four (4) years", "Eight (8) years"],
    choices: ["Six (6) years", "Two (2) years", "Four (4) years", "Eight (8) years"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 23,
    question: "Who is one of your state’s U.S. Senators now?",
    options: ["(Answer varies by state)", "George Washington", "Thomas Jefferson", "Abraham Lincoln"],
    choices: ["(Answer varies by state)", "George Washington", "Thomas Jefferson", "Abraham Lincoln"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 24,
    question: "How many voting members are in the House of Representatives?",
    options: ["Four hundred thirty-five (435)", "One hundred (100)", "Fifty (50)", "Nine (9)"],
    choices: ["Four hundred thirty-five (435)", "One hundred (100)", "Fifty (50)", "Nine (9)"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 25,
    question: "How long is a term for a member of the House?",
    options: ["Two (2) years", "Four (4) years", "Six (6) years", "Eight (8) years"],
    choices: ["Two (2) years", "Four (4) years", "Six (6) years", "Eight (8) years"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 26,
    question: "Why do U.S. Representatives serve shorter terms?",
    options: ["To more closely follow public opinion", "Because the Constitution requires it for Senators", "To avoid elections", "To serve for life"],
    choices: ["To more closely follow public opinion", "Because the Constitution requires it for Senators", "To avoid elections", "To serve for life"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 27,
    question: "How many Senators does each state have?",
    options: ["Two (2)", "One (1)", "Three (3)", "Five (5)"],
    choices: ["Two (2)", "One (1)", "Three (3)", "Five (5)"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 28,
    question: "Why does each state have two Senators?",
    options: ["Equal representation for small states", "Because of population", "Because the President decides", "Because the Supreme Court appoints them"],
    choices: ["Equal representation for small states", "Because of population", "Because the President decides", "Because the Supreme Court appoints them"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 29,
    question: "Name your U.S. Representative.",
    options: ["(Answer varies by district)", "The Chief Justice", "The Secretary of State", "The Vice President"],
    choices: ["(Answer varies by district)", "The Chief Justice", "The Secretary of State", "The Vice President"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 30,
    question: "What is the name of the Speaker of the House of Representatives now?",
    options: ["Check USCIS for current name", "George Washington", "Benjamin Franklin", "James Madison"],
    choices: ["Check USCIS for current name", "George Washington", "Benjamin Franklin", "James Madison"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 31,
    question: "Who does a U.S. Senator represent?",
    options: ["People of their state", "Only the President", "Only their political party", "Only Congress"],
    choices: ["People of their state", "Only the President", "Only their political party", "Only Congress"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 32,
    question: "Who elects U.S. Senators?",
    options: ["Citizens from their state", "The President", "The Supreme Court", "The Cabinet"],
    choices: ["Citizens from their state", "The President", "The Supreme Court", "The Cabinet"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 33,
    question: "Who does a member of the House represent?",
    options: ["Citizens in their congressional district", "Citizens of all states", "Only senators", "Only the President"],
    choices: ["Citizens in their congressional district", "Citizens of all states", "Only senators", "Only the President"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 34,
    question: "Who elects members of the House?",
    options: ["Citizens from their district", "The Vice President", "The Supreme Court", "The Cabinet"],
    choices: ["Citizens from their district", "The Vice President", "The Supreme Court", "The Cabinet"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 35,
    question: "Why do some states have more Representatives?",
    options: ["Because of the state’s population", "Because of the number of senators", "Because of the number of amendments", "Because of the number of judges"],
    choices: ["Because of the state’s population", "Because of the number of senators", "Because of the number of amendments", "Because of the number of judges"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 36,
    question: "The President is elected for how many years?",
    options: ["Four (4) years", "Two (2) years", "Six (6) years", "Eight (8) years"],
    choices: ["Four (4) years", "Two (2) years", "Six (6) years", "Eight (8) years"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 37,
    question: "The President can serve only two terms. Why?",
    options: ["22nd Amendment", "10th Amendment", "14th Amendment", "1st Amendment"],
    choices: ["22nd Amendment", "10th Amendment", "14th Amendment", "1st Amendment"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 38,
    question: "What is the name of the President now?",
    options: ["Check USCIS for current name", "George Washington", "Thomas Jefferson", "Abraham Lincoln"],
    choices: ["Check USCIS for current name", "George Washington", "Thomas Jefferson", "Abraham Lincoln"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 39,
    question: "What is the name of the Vice President now?",
    options: ["Check USCIS for current name", "Benjamin Franklin", "James Madison", "Alexander Hamilton"],
    choices: ["Check USCIS for current name", "Benjamin Franklin", "James Madison", "Alexander Hamilton"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 40,
    question: "If the President can no longer serve, who becomes President?",
    options: ["The Vice President", "The Speaker of the House", "The Chief Justice", "The Secretary of State"],
    choices: ["The Vice President", "The Speaker of the House", "The Chief Justice", "The Secretary of State"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 41,
    question: "Name one power of the President.",
    options: ["Vetoes bills", "Writes all laws", "Appoints state governors", "Creates new states alone"],
    choices: ["Vetoes bills", "Writes all laws", "Appoints state governors", "Creates new states alone"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 42,
    question: "Who is Commander in Chief of the military?",
    options: ["The President", "The Speaker of the House", "The Chief Justice", "The Secretary of Defense"],
    choices: ["The President", "The Speaker of the House", "The Chief Justice", "The Secretary of Defense"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 43,
    question: "Who signs bills to become laws?",
    options: ["The President", "The Vice President", "The Chief Justice", "The Senate Majority Leader"],
    choices: ["The President", "The Vice President", "The Chief Justice", "The Senate Majority Leader"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 44,
    question: "Who vetoes bills?",
    options: ["The President", "The Supreme Court", "The House of Representatives", "State governors"],
    choices: ["The President", "The Supreme Court", "The House of Representatives", "State governors"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 45,
    question: "Who appoints federal judges?",
    options: ["The President", "The Supreme Court", "State legislatures", "City mayors"],
    choices: ["The President", "The Supreme Court", "State legislatures", "City mayors"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 46,
    question: "Name one part of the Executive Branch.",
    options: ["Cabinet", "Senate", "Supreme Court", "House of Representatives"],
    choices: ["Cabinet", "Senate", "Supreme Court", "House of Representatives"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 47,
    question: "What does the President’s Cabinet do?",
    options: ["Advises the President", "Writes laws", "Runs state elections", "Approves Supreme Court cases"],
    choices: ["Advises the President", "Writes laws", "Runs state elections", "Approves Supreme Court cases"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 48,
    question: "Which is a Cabinet-level position?",
    options: ["Secretary of State", "Chief Justice", "Speaker of the House", "U.S. Senator"],
    choices: ["Secretary of State", "Chief Justice", "Speaker of the House", "U.S. Senator"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 49,
    question: "Why is the Electoral College important?",
    options: ["It decides who is elected President", "It appoints Supreme Court justices", "It writes the Constitution", "It passes state laws"],
    choices: ["It decides who is elected President", "It appoints Supreme Court justices", "It writes the Constitution", "It passes state laws"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 50,
    question: "Name one part of the Judicial Branch.",
    options: ["Supreme Court", "Cabinet", "Congress", "The President"],
    choices: ["Supreme Court", "Cabinet", "Congress", "The President"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 51,
    question: "What does the Judicial Branch do?",
    options: ["Decides if laws violate the Constitution", "Makes the federal budget", "Commands the military", "Prints money"],
    choices: ["Decides if laws violate the Constitution", "Makes the federal budget", "Commands the military", "Prints money"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 52,
    question: "What is the highest court in the United States?",
    options: ["Supreme Court", "Federal Appeals Court", "State Supreme Court", "District Court"],
    choices: ["Supreme Court", "Federal Appeals Court", "State Supreme Court", "District Court"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 53,
    question: "How many seats are on the Supreme Court?",
    options: ["Nine (9)", "Five (5)", "Seven (7)", "Thirteen (13)"],
    choices: ["Nine (9)", "Five (5)", "Seven (7)", "Thirteen (13)"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 54,
    question: "How many justices are usually needed to decide a case?",
    options: ["Five (5)", "Nine (9)", "Two (2)", "Ten (10)"],
    choices: ["Five (5)", "Nine (9)", "Two (2)", "Ten (10)"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 55,
    question: "How long do Supreme Court Justices serve?",
    options: ["For life", "Two years", "Four years", "Six years"],
    choices: ["For life", "Two years", "Four years", "Six years"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 56,
    question: "Why do Supreme Court Justices serve for life?",
    options: ["Independence from politics", "So they can write laws", "So they can run elections", "To increase state power"],
    choices: ["Independence from politics", "So they can write laws", "So they can run elections", "To increase state power"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 57,
    question: "Who is the Chief Justice of the United States now?",
    options: ["Check USCIS for current name", "The Vice President", "The Speaker of the House", "The Attorney General"],
    choices: ["Check USCIS for current name", "The Vice President", "The Speaker of the House", "The Attorney General"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 58,
    question: "Name one power that is only for the federal government.",
    options: ["Print money", "Issue driver’s licenses", "Provide public schooling", "Set zoning rules"],
    choices: ["Print money", "Issue driver’s licenses", "Provide public schooling", "Set zoning rules"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 59,
    question: "Name one power that is only for the states.",
    options: ["Driver’s licenses", "Make treaties", "Declare war", "Print money"],
    choices: ["Driver’s licenses", "Make treaties", "Declare war", "Print money"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 60,
    question: "What is the purpose of the 10th Amendment?",
    options: ["Powers not given to the federal government belong to the states or the people", "Gives the President veto power", "Creates the Supreme Court", "Ends slavery"],
    choices: ["Powers not given to the federal government belong to the states or the people", "Gives the President veto power", "Creates the Supreme Court", "Ends slavery"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 61,
    question: "Who is the Governor of your state now?",
    options: ["(Answer varies)", "The President", "The Chief Justice", "The Speaker of the House"],
    choices: ["(Answer varies)", "The President", "The Chief Justice", "The Speaker of the House"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 62,
    question: "What is the capital of your state?",
    options: ["(Answer varies)", "Washington, D.C.", "New York City", "Los Angeles"],
    choices: ["(Answer varies)", "Washington, D.C.", "New York City", "Los Angeles"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 63,
    question: "There are four amendments about who can vote. Describe one.",
    options: ["Citizens 18+ can vote", "Only landowners can vote", "Only men can vote", "Only people with college degrees can vote"],
    choices: ["Citizens 18+ can vote", "Only landowners can vote", "Only men can vote", "Only people with college degrees can vote"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 64,
    question: "Who can vote in federal elections, run for federal office, and serve on a jury?",
    options: ["U.S. citizens", "All visitors", "Only permanent residents", "Only state officials"],
    choices: ["U.S. citizens", "All visitors", "Only permanent residents", "Only state officials"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 65,
    question: "Name one right of everyone living in the U.S.",
    options: ["Freedom of speech", "Freedom to ignore taxes", "Freedom to break laws", "Freedom to vote in federal elections (for everyone)"],
    choices: ["Freedom of speech", "Freedom to ignore taxes", "Freedom to break laws", "Freedom to vote in federal elections (for everyone)"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 66,
    question: "What do we show loyalty to when we say the Pledge of Allegiance?",
    options: ["The United States", "The Supreme Court", "The President", "The Cabinet"],
    choices: ["The United States", "The Supreme Court", "The President", "The Cabinet"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 67,
    question: "Name one promise in the Oath of Allegiance.",
    options: ["Obey U.S. laws", "Vote in every election", "Become a police officer", "Own property in the U.S."],
    choices: ["Obey U.S. laws", "Vote in every election", "Become a police officer", "Own property in the U.S."],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 68,
    question: "How can people become U.S. citizens?",
    options: ["Naturalization", "By buying a house", "By getting a driver’s license", "By joining a political party"],
    choices: ["Naturalization", "By buying a house", "By getting a driver’s license", "By joining a political party"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 69,
    question: "Name one example of civic participation.",
    options: ["Vote", "Avoid paying taxes", "Ignore laws", "Refuse jury service"],
    choices: ["Vote", "Avoid paying taxes", "Ignore laws", "Refuse jury service"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 70,
    question: "Name one way Americans can serve their country.",
    options: ["Pay taxes", "Break laws", "Refuse to vote forever", "Ignore the Constitution"],
    choices: ["Pay taxes", "Break laws", "Refuse to vote forever", "Ignore the Constitution"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 71,
    question: "Why is it important to pay federal taxes?",
    options: ["It funds the government", "It elects the President", "It changes the Constitution", "It appoints judges"],
    choices: ["It funds the government", "It elects the President", "It changes the Constitution", "It appoints judges"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 72,
    question: "It is important for men 18–25 to register for Selective Service. Why?",
    options: ["Required by law", "So they can vote", "So they can be Senators", "So they can become judges"],
    choices: ["Required by law", "So they can vote", "So they can be Senators", "So they can become judges"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 73,
    question: "The colonists came to America for many reasons. Name one.",
    options: ["Religious freedom", "To end World War I", "To create the Supreme Court", "To build the Interstate Highway System"],
    choices: ["Religious freedom", "To end World War I", "To create the Supreme Court", "To build the Interstate Highway System"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 74,
    question: "Who lived in America before Europeans arrived?",
    options: ["Native Americans", "The British", "The French", "The Spanish"],
    choices: ["Native Americans", "The British", "The French", "The Spanish"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 75,
    question: "What group of people was taken and sold as slaves?",
    options: ["Africans", "Canadians", "Australians", "Japanese"],
    choices: ["Africans", "Canadians", "Australians", "Japanese"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 76,
    question: "What war did Americans fight to win independence?",
    options: ["American Revolution", "Civil War", "World War II", "Korean War"],
    choices: ["American Revolution", "Civil War", "World War II", "Korean War"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 77,
    question: "Name one reason Americans declared independence.",
    options: ["Taxation without representation", "To join Canada", "To create the United Nations", "To end the Cold War"],
    choices: ["Taxation without representation", "To join Canada", "To create the United Nations", "To end the Cold War"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 78,
    question: "Who wrote the Declaration of Independence?",
    options: ["Thomas Jefferson", "George Washington", "Benjamin Franklin", "James Madison"],
    choices: ["Thomas Jefferson", "George Washington", "Benjamin Franklin", "James Madison"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 79,
    question: "When was the Declaration adopted?",
    options: ["July 4, 1776", "July 4, 1789", "December 25, 1776", "January 1, 1800"],
    choices: ["July 4, 1776", "July 4, 1789", "December 25, 1776", "January 1, 1800"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 80,
    question: "Name one key event of the American Revolution.",
    options: ["Battle of Bunker Hill", "Attack on Pearl Harbor", "Signing the Emancipation Proclamation", "September 11 attacks"],
    choices: ["Battle of Bunker Hill", "Attack on Pearl Harbor", "Signing the Emancipation Proclamation", "September 11 attacks"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 81,
    question: "There were 13 original states. Which of the following was one of them?",
    options: ["Virginia", "California", "Hawaii", "Alaska"],
    choices: ["Virginia", "California", "Hawaii", "Alaska"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 82,
    question: "What founding document was written in 1787?",
    options: ["U.S. Constitution", "Declaration of Independence", "Emancipation Proclamation", "Gettysburg Address"],
    choices: ["U.S. Constitution", "Declaration of Independence", "Emancipation Proclamation", "Gettysburg Address"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 83,
    question: "The Federalist Papers supported the Constitution. Name one writer.",
    options: ["James Madison", "Martin Luther King Jr.", "Abraham Lincoln", "Susan B. Anthony"],
    choices: ["James Madison", "Martin Luther King Jr.", "Abraham Lincoln", "Susan B. Anthony"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 84,
    question: "Why were the Federalist Papers important?",
    options: ["They explained and supported the Constitution", "They ended the Civil War", "They started World War I", "They created the Bill of Rights"],
    choices: ["They explained and supported the Constitution", "They ended the Civil War", "They started World War I", "They created the Bill of Rights"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 85,
    question: "Benjamin Franklin is famous for many things. Name one.",
    options: ["Inventor", "Commander in Chief in WWII", "Wrote the Gettysburg Address", "Led the civil rights movement"],
    choices: ["Inventor", "Commander in Chief in WWII", "Wrote the Gettysburg Address", "Led the civil rights movement"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 86,
    question: "George Washington is famous for many things. Name one.",
    options: ["First President", "Wrote the Declaration of Independence", "Founded the first bank", "Ended slavery by amendment"],
    choices: ["First President", "Wrote the Declaration of Independence", "Founded the first bank", "Ended slavery by amendment"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 87,
    question: "Thomas Jefferson is famous for many things. Name one.",
    options: ["Wrote the Declaration of Independence", "Was Chief Justice", "Started the Interstate Highway System", "Fought in the Korean War"],
    choices: ["Wrote the Declaration of Independence", "Was Chief Justice", "Started the Interstate Highway System", "Fought in the Korean War"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 88,
    question: "James Madison is famous for many things. Name one.",
    options: ["Father of the Constitution", "Wrote the Star-Spangled Banner", "Discovered electricity", "Purchased Alaska"],
    choices: ["Father of the Constitution", "Wrote the Star-Spangled Banner", "Discovered electricity", "Purchased Alaska"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 89,
    question: "Alexander Hamilton is famous for many things. Name one.",
    options: ["First Secretary of the Treasury", "First Chief Justice", "President during WWII", "Leader of the women’s rights movement"],
    choices: ["First Secretary of the Treasury", "First Chief Justice", "President during WWII", "Leader of the women’s rights movement"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 90,
    question: "What territory did the U.S. buy from France in 1803?",
    options: ["Louisiana Territory", "Alaska Territory", "Hawaii Territory", "Puerto Rico"],
    choices: ["Louisiana Territory", "Alaska Territory", "Hawaii Territory", "Puerto Rico"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 91,
    question: "Name one war fought by the U.S. in the 1800s.",
    options: ["Civil War", "World War I", "Korean War", "Persian Gulf War"],
    choices: ["Civil War", "World War I", "Korean War", "Persian Gulf War"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 92,
    question: "What war was between the North and the South?",
    options: ["Civil War", "American Revolution", "World War II", "Vietnam War"],
    choices: ["Civil War", "American Revolution", "World War II", "Vietnam War"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 93,
    question: "Name one important event of the Civil War.",
    options: ["Emancipation Proclamation", "Signing of the Constitution", "Attack on Pearl Harbor", "September 11 attacks"],
    choices: ["Emancipation Proclamation", "Signing of the Constitution", "Attack on Pearl Harbor", "September 11 attacks"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 94,
    question: "Abraham Lincoln is famous for many things. Name one.",
    options: ["Freed the slaves", "Wrote the Federalist Papers", "Was the first Secretary of State", "Created the Bill of Rights"],
    choices: ["Freed the slaves", "Wrote the Federalist Papers", "Was the first Secretary of State", "Created the Bill of Rights"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 95,
    question: "What did the Emancipation Proclamation do?",
    options: ["Freed the slaves in Confederate states", "Ended World War I", "Gave women the right to vote", "Created the Supreme Court"],
    choices: ["Freed the slaves in Confederate states", "Ended World War I", "Gave women the right to vote", "Created the Supreme Court"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 96,
    question: "What U.S. war ended slavery?",
    options: ["The Civil War", "The American Revolution", "The War of 1812", "World War II"],
    choices: ["The Civil War", "The American Revolution", "The War of 1812", "World War II"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 97,
    question: "What amendment says all persons born or naturalized in the U.S. are citizens?",
    options: ["14th Amendment", "15th Amendment", "19th Amendment", "22nd Amendment"],
    choices: ["14th Amendment", "15th Amendment", "19th Amendment", "22nd Amendment"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 98,
    question: "When did all men get the right to vote?",
    options: ["15th Amendment (1870)", "19th Amendment (1920)", "22nd Amendment (1951)", "10th Amendment (1791)"],
    choices: ["15th Amendment (1870)", "19th Amendment (1920)", "22nd Amendment (1951)", "10th Amendment (1791)"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 99,
    question: "Name one leader of the women’s rights movement in the 1800s.",
    options: ["Susan B. Anthony", "Dwight Eisenhower", "Thomas Jefferson", "John Jay"],
    choices: ["Susan B. Anthony", "Dwight Eisenhower", "Thomas Jefferson", "John Jay"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 100,
    question: "Name one war fought by the U.S. in the 1900s.",
    options: ["World War II", "American Revolution", "War of 1812", "Spanish conquest"],
    choices: ["World War II", "American Revolution", "War of 1812", "Spanish conquest"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 101,
    question: "Why did the U.S. enter World War I?",
    options: ["Germany attacked U.S. ships", "To buy Louisiana Territory", "To end slavery", "To stop the Great Depression"],
    choices: ["Germany attacked U.S. ships", "To buy Louisiana Territory", "To end slavery", "To stop the Great Depression"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 102,
    question: "When did women get the right to vote?",
    options: ["1920", "1870", "1787", "2001"],
    choices: ["1920", "1870", "1787", "2001"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 103,
    question: "What was the Great Depression?",
    options: ["A long economic recession", "A war between North and South", "A document written in 1787", "A civil rights law"],
    choices: ["A long economic recession", "A war between North and South", "A document written in 1787", "A civil rights law"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 104,
    question: "When did the Great Depression begin?",
    options: ["1929", "1776", "1803", "2001"],
    choices: ["1929", "1776", "1803", "2001"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 105,
    question: "Who was President during the Great Depression and World War II?",
    options: ["Franklin Roosevelt", "George Washington", "Thomas Jefferson", "Dwight Eisenhower"],
    choices: ["Franklin Roosevelt", "George Washington", "Thomas Jefferson", "Dwight Eisenhower"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 106,
    question: "Why did the U.S. enter World War II?",
    options: ["Japanese attack on Pearl Harbor", "Germany attacked U.S. ships", "To stop the spread of communism in Korea", "To force Iraqi troops out of Kuwait"],
    choices: ["Japanese attack on Pearl Harbor", "Germany attacked U.S. ships", "To stop the spread of communism in Korea", "To force Iraqi troops out of Kuwait"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 107,
    question: "Dwight Eisenhower is known for many things. Name one.",
    options: ["Created Interstate Highway System", "Wrote the Declaration of Independence", "Led the women’s rights movement", "Was the first Secretary of the Treasury"],
    choices: ["Created Interstate Highway System", "Wrote the Declaration of Independence", "Led the women’s rights movement", "Was the first Secretary of the Treasury"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 108,
    question: "Who was the U.S. rival during the Cold War?",
    options: ["Soviet Union (USSR)", "France", "Canada", "Japan"],
    choices: ["Soviet Union (USSR)", "France", "Canada", "Japan"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 109,
    question: "During the Cold War, what was a top U.S. concern?",
    options: ["Communism", "Feudalism", "Mercantilism", "Monarchy"],
    choices: ["Communism", "Feudalism", "Mercantilism", "Monarchy"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 110,
    question: "Why did the U.S. enter the Korean War?",
    options: ["To stop the spread of communism", "To buy Louisiana Territory", "To end the Great Depression", "To write the Constitution"],
    choices: ["To stop the spread of communism", "To buy Louisiana Territory", "To end the Great Depression", "To write the Constitution"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 111,
    question: "Why did the U.S. enter the Vietnam War?",
    options: ["To stop the spread of communism", "To force Iraqi troops out of Kuwait", "Because of Pearl Harbor", "Because Germany attacked U.S. ships in WWI"],
    choices: ["To stop the spread of communism", "To force Iraqi troops out of Kuwait", "Because of Pearl Harbor", "Because Germany attacked U.S. ships in WWI"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 112,
    question: "What did the civil rights movement do?",
    options: ["Fought to end racial discrimination", "Created the Constitution", "Ended the Cold War", "Declared independence from France"],
    choices: ["Fought to end racial discrimination", "Created the Constitution", "Ended the Cold War", "Declared independence from France"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 113,
    question: "Martin Luther King Jr. is famous for many things. Name one.",
    options: ["Fought for civil rights", "First President", "Wrote the Federalist Papers", "Purchased Louisiana Territory"],
    choices: ["Fought for civil rights", "First President", "Wrote the Federalist Papers", "Purchased Louisiana Territory"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 114,
    question: "Why did the U.S. enter the Persian Gulf War?",
    options: ["To force Iraqi troops out of Kuwait", "To stop the spread of communism", "Because of Pearl Harbor", "To end slavery"],
    choices: ["To force Iraqi troops out of Kuwait", "To stop the spread of communism", "Because of Pearl Harbor", "To end slavery"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 115,
    question: "What major event happened on September 11, 2001?",
    options: ["Terrorist attacks", "The Constitution was written", "The Civil War ended", "The Great Depression began"],
    choices: ["Terrorist attacks", "The Constitution was written", "The Civil War ended", "The Great Depression began"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 116,
    question: "Name one American military conflict after 9/11.",
    options: ["Afghanistan", "World War I", "Civil War", "War of 1812"],
    choices: ["Afghanistan", "World War I", "Civil War", "War of 1812"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 117,
    question: "Name one American Indian tribe.",
    options: ["Cherokee", "Vikings", "Romans", "Mongols"],
    choices: ["Cherokee", "Vikings", "Romans", "Mongols"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 118,
    question: "Name one U.S. innovation.",
    options: ["Light bulb", "Pyramids", "Printing press (15th century Europe)", "Compass (ancient China)"],
    choices: ["Light bulb", "Pyramids", "Printing press (15th century Europe)", "Compass (ancient China)"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 119,
    question: "What is the capital of the United States?",
    options: ["Washington, D.C.", "New York City", "Los Angeles", "Philadelphia"],
    choices: ["Washington, D.C.", "New York City", "Los Angeles", "Philadelphia"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 120,
    question: "Where is the Statue of Liberty?",
    options: ["Liberty Island", "Washington, D.C.", "Boston Harbor", "San Francisco Bay"],
    choices: ["Liberty Island", "Washington, D.C.", "Boston Harbor", "San Francisco Bay"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 121,
    question: "Why does the flag have 13 stripes?",
    options: ["Because of the 13 original colonies", "Because there are 13 states today", "Because there are 13 amendments", "Because there are 13 presidents"],
    choices: ["Because of the 13 original colonies", "Because there are 13 states today", "Because there are 13 amendments", "Because there are 13 presidents"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 122,
    question: "Why does the flag have 50 stars?",
    options: ["One star for each state", "One star for each President", "One star for each amendment", "One star for each holiday"],
    choices: ["One star for each state", "One star for each President", "One star for each amendment", "One star for each holiday"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 123,
    question: "What is the national anthem?",
    options: ["The Star-Spangled Banner", "America the Beautiful", "God Bless America", "Yankee Doodle"],
    choices: ["The Star-Spangled Banner", "America the Beautiful", "God Bless America", "Yankee Doodle"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 124,
    question: "What was the first national motto?",
    options: ['E Pluribus Unum ("Out of many, one")', "In God We Trust", "Liberty or Death", "United We Stand"],
    choices: ['E Pluribus Unum ("Out of many, one")', "In God We Trust", "Liberty or Death", "United We Stand"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 125,
    question: "What is Independence Day?",
    options: ["Holiday celebrating independence from Britain", "Holiday honoring veterans", "Holiday honoring soldiers who died", "Holiday celebrating the Constitution"],
    choices: ["Holiday celebrating independence from Britain", "Holiday honoring veterans", "Holiday honoring soldiers who died", "Holiday celebrating the Constitution"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 126,
    question: "Which of the following is a national U.S. holiday?",
    options: ["Thanksgiving", "Halloween", "Valentine’s Day", "Mother’s Day"],
    choices: ["Thanksgiving", "Halloween", "Valentine’s Day", "Mother’s Day"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 127,
    question: "What is Memorial Day?",
    options: ["Honors soldiers who died in service", "Honors U.S. veterans", "Celebrates independence from Britain", "Celebrates the Constitution"],
    choices: ["Honors soldiers who died in service", "Honors U.S. veterans", "Celebrates independence from Britain", "Celebrates the Constitution"],
    answer: 0,
    answerIndex: 0,
  },
  {
    id: 128,
    question: "What is Veterans Day?",
    options: ["Honors U.S. Veterans", "Honors soldiers who died in service", "Celebrates independence from Britain", "Celebrates the Constitution"],
    choices: ["Honors U.S. Veterans", "Honors soldiers who died in service", "Celebrates independence from Britain", "Celebrates the Constitution"],
    answer: 0,
    answerIndex: 0,
  },
];

export default questions;
